.PHONY: clean All

All:
	@echo "----------Building project:[ wk6lab2prg2 - Debug ]----------"
	@$(MAKE) -f  "wk6lab2prg2.mk"
clean:
	@echo "----------Cleaning project:[ wk6lab2prg2 - Debug ]----------"
	@$(MAKE) -f  "wk6lab2prg2.mk" clean
