.PHONY: clean All

All:
	@echo "----------Building project:[ wk6Lab2prg1 - Debug ]----------"
	@$(MAKE) -f  "wk6Lab2prg1.mk"
clean:
	@echo "----------Cleaning project:[ wk6Lab2prg1 - Debug ]----------"
	@$(MAKE) -f  "wk6Lab2prg1.mk" clean
